### ISSUE TITLE
TODO list before the first release

### ISSUE THREAD

**Issue by fhh2626** [fhh2626/BFEE2#30]
- [x] Option to generate parallel runs in the geometrical route
- [x] Documentation of python API
- [x] Generate files for extending simulations in the geometrical route
- [x] Make Help option work
- [x] Make Add and Clear button Grey when using Amber FF
- [x] When cancel the directory selection, BFEE2 should do nothing
- [x] Generate readme file in the BFEE dir
- [x] Rename .conf files
- [x] Do not overwrite ./BFEE folder, raise an Error instead

**Comment by fhh2626** [comment]
- [ ] Address spherical angle issue for the membrane protein

**Comment by fhh2626** [comment]
- [ ] Make sure there is at least 1 FF file when using the CHARMM FF

**Comment by fhh2626** [comment]
- [ ] Generate scripts for modeling amber files
- [ ] Correct file name of scripts

**Comment by fhh2626** [comment]
- [ ] Rename scripts

**Comment by fhh2626** [comment]
- [ ] BFEEGromacs should not overwrite 
- [ ] BFEEGromacs scripts generate correct file names of *.tpr

**Comment by fhh2626** [comment]
- [ ] change "Geometric" to "Geometrical" in the GUI

**Comment by fhh2626** [comment]
- [ ] distribute latest dev version on PyPI

**Comment by fhh2626** [comment]
Everything finished. Close this issue.
