### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by fhh2626** [fhh2626/BFEE2#38]
- [x] increase force constants used in pinning down the protein
- [ ] add a script, letting user to use the equilibrated structure as the reference
- [x] correct periodicity of polarPhi
